apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"


# if we taint the node then the pods will not be scheduled into that tainted node
# if we tolerate the same node by mentioning tainted "key value description", then the pods may schedule into the same node but not 100% guarantee.
